create table client
(
    id         int8 generated by default as identity,
    brand_car  varchar(255),
    email      varchar(255),
    number_car varchar(255),
    password   varchar(255),
    username   varchar(255),
    primary key (id)
);

create table status
(
    id   int8 not null,
    name varchar(255),
    primary key (id)
);

create table client_roles
(
    client_id int8 not null,
    roles_id  int8 not null,
    primary key (client_id, roles_id)
);

alter table if exists client_roles
    add constraint client_fk
    foreign key (client_id) references client;

alter table if exists client_roles
    add constraint status_fk
    foreign key (roles_id) references status;



