create table order_entity
(
    id            int8 generated by default as identity,
    brand_car     varchar(255),
    cost_car_wash int4,
    email         varchar(255),
    end_time      TIMESTAMP,
    number_car    varchar(255),
    start_time    TIMESTAMP,
    username      varchar(255),
    primary key (id)
);

create table wash_option
(
    id   int8 generated by default as identity,
    cost int4 not null,
    name varchar(255),
    time int4 not null,
    primary key (id)
);

create table order_entity_wash_options
(
    order_entity_id int8 not null,
    wash_options_id int8 not null,
    primary key (order_entity_id, wash_options_id)
);

alter table if exists order_entity_wash_options
    add constraint wash_option_fk
    foreign key (wash_options_id) references wash_option;

alter table if exists order_entity_wash_options
    add constraint order_entity_fk
    foreign key (order_entity_id) references order_entity;


